Downgrade exec-maven-plugin to avoid JasperException.
org.apache.jasper.JasperException: PWC6345: There is an error in
invoking javac.  A full JDK (not just JRE) is required